### ISSUE TITLE
Nested lists do not render properly

### ISSUE THREAD

**Issue by obuseme** [mdiep/MMMarkdown#97]
Hello, I'm loving MMMarkdown, thanks!

I found that nested lists are not handled correctly, for example, this markdown:

```
* 1
  * 2
* 3
```

"2" should be an indented bullet, instead, it's just treated as a `<li>` at the same level as "1" and "3".

**Comment by mdiep** [comment]
The Markdown spec is totally ambiguous about this input. It doesn't specify how many spaces are required to form a nested list. [Some implementations require 4; others require 2.](http://johnmacfarlane.net/babelmark2/?normalize=1&text=*+1%0A++*+2%0A*+3). It looks like people may be settling on 2 now because of CommonMark, so I'll leave this open with the intention of switching to that.

**Comment by obuseme** [comment]
Thanks for the quick response!  That makes sense.  From an end user of this library perspective, I think two things could make it more awesome, documentation about supported markdown. Without looking at the code, how should I have known how to get nested lists?  The second thing, would be, since there's an option to designate "GitHubFlavored" markdown, then I think it should be kept in-sync with that, and there it's pretty clearly https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#lists defined that two spaces indent a list.  How can I help?  Thanks again, this is great!

**Comment by mdiep** [comment]
It should be pretty easy to change [the code](https://github.com/mdiep/MMMarkdown/blob/b05594c969d49b26abd8e0a386d705f041d33a1c/Source/MMParser.m#L743) to use 2 spaces for lists if you wanted to open a PR. You'd also need to adjust any failing tests and possibly add a test like your example above.
